nclavis:
  db-connection-info:
    request-hash-key: b75f849271970d6a00d4d2e977b5777cf7695bf5
    
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
