spring:
  cache:
    jcache:
      config: classpath:config/ehcache.xml
  profiles:
    active: default
  jackson:
    serialization:
      indent_output: true
  task:
    execution:
      pool:
        core-size: 8
        max-size: 8

server:
  tomcat:
    max-threads: 200