spring:
  cache:
    jcache:
      config: classpath:config/ehcache.xml
  profiles:
    active: default
  jackson:
    serialization:
      indent_output: true
    
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
