spring:
  datasource:
    driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
    url: jdbc:cubrid:10.106.145.189:30000:nhnculture:::?charset=utf-8
    username: nhnculture
    password: nh0)3#nc
    
  pid:
    file: /home1/irteam/deploy/mooc/api.pid
    
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true